# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

 # 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0401.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0402.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0403.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0404.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0405.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0406.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0407.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0408.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0409.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0410.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0411.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0412.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0413.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0414.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0415.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0416.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0417.txt

 # 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.yml
    
 # 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adskd/ffasdc1/main/70m%2Bv2RAY
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adskd/ffasdc1/main/new%3Dpac
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/adskd/ffasdc1/main/12345

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 订阅链接1
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/learnhard-cn/free_proxy_ss/main/v2ray/proxy.txt

# 订阅链接2
- type: subscribe
  options:
    url: https://jiang.netlify.app

# 订阅链接3
- type: subscribe
  options:
    url: https://telegram-kkv2r-d320.netlify.app

# 订阅链接5
#自动动态更新
- type: subscribe
  options:
    url: http://120.92.132.166:8888/down/QBXFCG5vwkzr
- type: subscribe
  options:
    url: https://suo.yt/JMvfwOT
#自动动态更新    
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=d309c6921bbd7d0d
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.com/
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/hotsymbol/vpnsetting/master/v2rayopen
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://iwxf.netlify.app/
- type: subscribe
  options:
    url: https://youlianboshi.netlify.com/
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Day.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Sub.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0411.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/RaymondHarris971/ssrsub/master/9a075bdee5.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
- type: subscribe
  options:
    url: https://jiang.netlify.com/
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
  options:
    url: https://youlianboshi.netlify.app/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# 网页模糊抓取1
- type: webfuzz
  options:
    url: https://github.com/Alvin9999/new-pac/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

# 网页模糊抓取2
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/
- type: webfuzz
  options:
    url: https://www.freefq.com/d/file/v2ray/20210409/ae29c1c14821f778de249eb29201d34f.htm
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ss/ss.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/ruanfei/ShadowsocksRRShare/master/ssr/ssr.txt
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/52bp/52bp.github.io/master/freesite.html

 # 网页模糊抓取3
- type: webfuzz
  options:
    url: http://www.gaofumei.net/networks/

 # 网页模糊抓取4
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/zzsnn/proxypool/master/ss.txt

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
# tg频道抓取1
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: ssList
    num: 200
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200
- type: tgchannel
  options:
    channel: ssrlists
    num: 200
- type: tgchannel
  options:
    channel: ssrshares
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: ssrtool
    num: 100
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 100
- type: tgchannel
  options:
    channel: vmessr
    num: 200
- type: tgchannel
  options:
    channel: FreeSSR666
    num: 200
- type: tgchannel
  options:
    channel: fanqiang666
    num: 200
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 
    
#tg频道抓取2
- type: jingpingziyuanfenxiang
  options:
    channel: ssrList
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: ssList
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: SSRSUB
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: FreeSSRNode
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: ssrlists
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: ssrshares
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: V2List
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: ssrtool
    num: 100
- type: jingpingziyuanfenxiang
  options:
    channel: ssrtool_crack
    num: 100
- type: jingpingziyuanfenxiang
  options:
    channel: vmessr
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: FreeSSR666
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: fanqiang666
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: jiedianfenxiang
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: freeshadowsock
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: V2subscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: Clashsubscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: QuantumultXsubscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: Surge2subscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: Surge3subscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: Surge4subscription
    num: 200
- type: jingpingziyuanfenxiang
  options:
    channel: Surfboardsubscription
    num: 200

#tg频道抓取3
- type: V2List
  options:
    channel: ssrList
    num: 200
- type: V2List
  options:
    channel: ssList
    num: 200
- type: V2List
  options:
    channel: SSRSUB
    num: 200
- type: V2List
  options:
    channel: FreeSSRNode
    num: 200
- type: V2List
  options:
    channel: ssrlists
    num: 200
- type: V2List
  options:
    channel: ssrshares
    num: 200
- type: V2List
  options:
    channel: V2List
    num: 200
- type: V2List
  options:
    channel: ssrtool
    num: 100
- type: V2List
  options:
    channel: ssrtool_crack
    num: 100
- type: V2List
  options:
    channel: vmessr
    num: 200
- type: V2List
  options:
    channel: FreeSSR666
    num: 200
- type: V2List
  options:
    channel: fanqiang666
    num: 200
- type: V2List
  options:
    channel: jiedianfenxiang
    num: 200
- type: V2List
  options:
    channel: freeshadowsock
    num: 200
- type: V2List
  options:
    channel: V2subscription
    num: 200
- type: V2List
  options:
    channel: Clashsubscription
    num: 200
- type: V2List
  options:
    channel: QuantumultXsubscription
    num: 200
- type: V2List
  options:
    channel: Surge2subscription
    num: 200
- type: V2List
  options:
    channel: Surge3subscription
    num: 200
- type: V2List
  options:
    channel: Surge4subscription
    num: 200
- type: V2List
  options:
    channel: Surfboardsubscription
    num: 200

#tg频道抓取4
- type: ssList
  options:
    channel: ssrList
    num: 200
- type: ssList
  options:
    channel: ssList
    num: 200
- type: ssList
  options:
    channel: SSRSUB
    num: 200
- type: ssList
  options:
    channel: FreeSSRNode
    num: 200
- type: ssList
  options:
    channel: ssrlists
    num: 200
- type: ssList
  options:
    channel: ssrshares
    num: 200
- type: ssList
  options:
    channel: V2List
    num: 200
- type: ssList
  options:
    channel: ssrtool
    num: 100
- type: ssList
  options:
    channel: ssrtool_crack
    num: 100
- type: ssList
  options:
    channel: vmessr
    num: 200
- type: ssList
  options:
    channel: FreeSSR666
    num: 200
- type: ssList
  options:
    channel: fanqiang666
    num: 200
- type: ssList
  options:
    channel: jiedianfenxiang
    num: 200
- type: ssList
  options:
    channel: freeshadowsock
    num: 200
- type: ssList
  options:
    channel: V2subscription
    num: 200
- type: ssList
  options:
    channel: Clashsubscription
    num: 200
- type: ssList
  options:
    channel: QuantumultXsubscription
    num: 200
- type: ssList
  options:
    channel: Surge2subscription
    num: 200
- type: ssList
  options:
    channel: Surge3subscription
    num: 200
- type: ssList
  options:
    channel: Surge4subscription
    num: 200
- type: ssList
  options:
    channel: Surfboardsubscription
    num: 200

#tg频道抓取4
- type: ssrList
  options:
    channel: ssrList
    num: 200
- type: ssrList
  options:
    channel: ssList
    num: 200
- type: ssrList
  options:
    channel: SSRSUB
    num: 200
- type: ssrList
  options:
    channel: FreeSSRNode
    num: 200
- type: ssrList
  options:
    channel: ssrlists
    num: 200
- type: ssrList
  options:
    channel: ssrshares
    num: 200
- type: ssrList
  options:
    channel: V2List
    num: 200
- type: ssrList
  options:
    channel: ssrtool
    num: 100
- type: ssrList
  options:
    channel: ssrtool_crack
    num: 100
- type: ssrList
  options:
    channel: vmessr
    num: 200
- type: ssrList
  options:
    channel: FreeSSR666
    num: 200
- type: ssrList
  options:
    channel: fanqiang666
    num: 200
- type: ssrList
  options:
    channel: jiedianfenxiang
    num: 200
- type: ssrList
  options:
    channel: freeshadowsock
    num: 200
- type: ssrList
  options:
    channel: V2subscription
    num: 200
- type: ssrList
  options:
    channel: Clashsubscription
    num: 200
- type: ssrList
  options:
    channel: QuantumultXsubscription
    num: 200
- type: ssrList
  options:
    channel: Surge2subscription
    num: 200
- type: ssrList
  options:
    channel: Surge3subscription
    num: 200
- type: ssrList
  options:
    channel: Surge4subscription
    num: 200
- type: ssrList
  options:
    channel: Surfboardsubscription
    num: 200

#tg频道抓取5
- type: MeAndMyPY
  options:
    channel: ssrList
    num: 200
- type: MeAndMyPY
  options:
    channel: ssList
    num: 200
- type: MeAndMyPY
  options:
    channel: SSRSUB
    num: 200
- type: MeAndMyPY
  options:
    channel: FreeSSRNode
    num: 200
- type: MeAndMyPY
  options:
    channel: ssrlists
    num: 200
- type: MeAndMyPY
  options:
    channel: ssrshares
    num: 200
- type: MeAndMyPY
  options:
    channel: V2List
    num: 200
- type: MeAndMyPY
  options:
    channel: ssrtool
    num: 100
- type: MeAndMyPY
  options:
    channel: ssrtool_crack
    num: 100
- type: MeAndMyPY
  options:
    channel: vmessr
    num: 200
- type: MeAndMyPY
  options:
    channel: FreeSSR666
    num: 200
- type: MeAndMyPY
  options:
    channel: fanqiang666
    num: 200
- type: MeAndMyPY
  options:
    channel: jiedianfenxiang
    num: 200
- type: MeAndMyPY
  options:
    channel: freeshadowsock
    num: 200
- type: MeAndMyPY
  options:
    channel: V2subscription
    num: 200
- type: MeAndMyPY
  options:
    channel: Clashsubscription
    num: 200
- type: MeAndMyPY
  options:
    channel: QuantumultXsubscription
    num: 200
- type: MeAndMyPY
  options:
    channel: Surge2subscription
    num: 200
- type: MeAndMyPY
  options:
    channel: Surge3subscription
    num: 200
- type: MeAndMyPY
  options:
    channel: Surge4subscription
    num: 200
- type: MeAndMyPY
  options:
    channel: Surfboardsubscription
    num: 200

#tg频道抓取5
- type: lanxhcom
  options:
    channel: ssrList
    num: 200
- type: lanxhcom
  options:
    channel: ssList
    num: 200
- type: lanxhcom
  options:
    channel: SSRSUB
    num: 200
- type: lanxhcom
  options:
    channel: FreeSSRNode
    num: 200
- type: lanxhcom
  options:
    channel: ssrlists
    num: 200
- type: lanxhcom
  options:
    channel: ssrshares
    num: 200
- type: lanxhcom
  options:
    channel: V2List
    num: 200
- type: lanxhcom
  options:
    channel: ssrtool
    num: 100
- type: lanxhcom
  options:
    channel: ssrtool_crack
    num: 100
- type: lanxhcom
  options:
    channel: vmessr
    num: 200
- type: lanxhcom
  options:
    channel: FreeSSR666
    num: 200
- type: lanxhcom
  options:
    channel: fanqiang666
    num: 200
- type: lanxhcom
  options:
    channel: jiedianfenxiang
    num: 200
- type: lanxhcom
  options:
    channel: freeshadowsock
    num: 200
- type: lanxhcom
  options:
    channel: V2subscription
    num: 200
- type: lanxhcom
  options:
    channel: Clashsubscription
    num: 200
- type: lanxhcom
  options:
    channel: QuantumultXsubscription
    num: 200
- type: lanxhcom
  options:
    channel: Surge2subscription
    num: 200
- type: lanxhcom
  options:
    channel: Surge3subscription
    num: 200
- type: lanxhcom
  options:
    channel: Surge4subscription
    num: 200
- type: lanxhcom
  options:
    channel: Surfboardsubscription
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 翻墙党论坛抓取1
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-51-1.html

# 翻墙党论坛抓取2
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html

# 翻墙党，后面的东西都无需修改
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=50&auth=0
    num: 200
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=2&auth=0
    num: 200
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum.php?mod=rss&fid=36&auth=0
    num: 200

# clash格式订阅链接 
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options: